SELECT FINAL_STATUS,* FROM DATAMIGRATION.DEMO_USER.DATA_INGESTION_LOG_TABLE ORDER BY BATCH_ID DESC LIMIT 5;

SELECT * FROM DATAMIGRATION.DEMO_USER.DATA_INGESTION_CONFIG_TABLE

;
DROP TABLE ORDERS;
DROP TABLE CUSTOMER;
DROP TABLE LINEITEM;    
DROP TABLE PEOPLE;

DROP TABLE PART;

SELECT COUNT(*) FROM DATAMIGRATION.DEMO_USER.PART;


--UPDATE DATA_INGESTION_CONFIG_TABLE SET TABLE_EXISTS='NO' 